[build]
builder = "nixpacks"
buildCommand = "chmod +x ./node_modules/.bin/vite && npm ci && npm run build"

[deploy]
startCommand = "php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "never"

[phases.setup]
nixPkgs = ['nodejs', 'npm', 'php']
cmds = [
    "mkdir -p public/build",
    "chmod -R 777 public/build",
    "chmod -R 777 node_modules"
]
